## Basic Operations on Images


In [2]:
import cv2
import numpy as np


In [13]:
img = cv2.imread('messi5.jpg')
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
px = img[100,100]
print (px)

[ 33   1 214]


In [5]:
blue = img[100,100,0]
print (blue)

33


In [ ]:
img[100:200,100:200] = [255,255,255]
print (img[100,100])

[255 255 255]


In [ ]:
img.item(10,10,2)

255

In [10]:
img.itemset((10,10,2),100)
img.item(10,10,2)

100

In [ ]:
img[100:200,100:200, 2] = 255
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[ 33   1 255]


In [ ]:
print(img.shape)
print(img.size)
print(img.dtype)

In [ ]:
b,g,r = cv2.split(img)
img = cv2.merge((b,g,r))


In [ ]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
BLUE = [255,0,0]
img1 = cv2.imread('opencv_logo.png')
replicate = cv2.copyMakeBorder(img1,10,10,10,10,cv2.BORDER_REPLICATE)
reflect = cv2.copyMakeBorder(img1,10,10,10,10,cv2.BORDER_REFLECT)
reflect101 = cv2.copyMakeBorder(img1,10,10,10,10,cv2.BORDER_REFLECT_101)
wrap = cv2.copyMakeBorder(img1,10,10,10,10,cv2.BORDER_WRAP)
constant= cv2.copyMakeBorder(img1,10,10,10,10,cv2.BORDER_CONSTANT,value=BLUE)
plt.subplot(231),plt.imshow(img1,'gray'),plt.title('ORIGINAL')
plt.subplot(232),plt.imshow(replicate,'gray'),plt.title('REPLICATE')
plt.subplot(233),plt.imshow(reflect,'gray'),plt.title('REFLECT')
plt.subplot(234),plt.imshow(reflect101,'gray'),plt.title('REFLECT_101')
plt.subplot(235),plt.imshow(wrap,'gray'),plt.title('WRAP')
plt.subplot(236),plt.imshow(constant,'gray'),plt.title('CONSTANT')
plt.show()